language: ruby
rvm:
  - 2.3.1
env:
  - DB=sqlite
before_script:
  - mysql -e 'create database test;'
script:
  - RAILS_ENV=test bundle exec rake db:migrate:reset --trace
  - RAILS_ENV=test bundele exec rake db:reset --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec/
addons:
  code_climate:
    repo_token: 5007c33a7452537f5c3b2bee717a1aa7edf79f4e3a173c295ca52ad6d9ee911b